### ISSUE TITLE
error occured when extracting the file

### ISSUE THREAD

**Issue by mingminzhen** [nightrome/cocostuff10k#10]
I download the cocostuff-10k-v1.1.zip. when i extract it, error occured.
Could you help check it?

**Comment by nightrome** [comment]
Hi,
I successfully downloaded that file from [here](http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/cocostuff-10k-v1.1.zip) and unzipped it using Ubuntu's default Archive Manager. I'd suggest downloading it again.
Furthermore, be aware that from ~1. September we will start the [COCO 2017 Stuff Segmentation Challenge](cocodataset.org/dataset.htm#stuff-challenge2017) with 65K COCO-Stuff images, so you might want to work on that.

**Comment by mingminzhen** [comment]
I have re downloaded the file again and again. But even though i unzip the file andthere are 1000 files for image dir and annotation dir, some .mat file is unreadable in matlab. 
like:
Error using load
Cannot read file
Documents/cocostuff/dataset/annotations/COCO_train2014_000000011349.mat.

**Comment by nightrome** [comment]
Hi,
I have just tested that particular file and for me it works very well. Please download it from [here](https://ufile.io/lqsop) and check again (link valid for 30 days).
The file is stored as a v7.0 Matlab file ("level 5"). This format has been used since Matlab R2006a. Do you by any chance have an older Matlab version? Could you tell me what OS and Matlab version you are using?
If that does not work, try using the .json file with the same annotations.

**Comment by mingminzhen** [comment]
I'm using Matlab R2015b and Centos7. But I can load other .mat files in downloaded files. In addition,
I am trying to unzip it in Win10. But it still fails. 

How can i use the .json file, could you provide some scripts like "convertAnnotationsDeeplab".

**Comment by nightrome** [comment]
Yeah that is true. The inconsistency is weird.
I suggest you wait 2-3 days until we release the [COCO 2017 Stuff Segmentation Challenge annotations](http://mscoco.org/dataset/#download).
Then [this script](https://github.com/nightrome/coco/blob/master/PythonAPI/cocostuff/cocoSegmentationToPngDemo.py) will solve all your problems, converting .json to .pngs.

**Comment by mingminzhen** [comment]
ok, thanks!

**Comment by nightrome** [comment]
Now the train/val annotations have been released at [http://cocodataset.org/dataset.htm#download](http://cocodataset.org/dataset.htm#download)

**Comment by mingminzhen** [comment]
I am trying to download the train2017.zip. When I have downloaded it and extract it, errors occur. I do not know why. It is weird. The .zip file is too large. Could you split it into several files or put them into dropbox or other places?

**Comment by nightrome** [comment]
Hi,
that is indeed very weird and I think it must be a problem with your zip tool. You could obviously install another one.
Luckily we are now using Google Cloud Storage, so there is another way: Go to http://cocodataset.org/dataset.htm#download and click on "gsutil rsync". There you will find the instructions how to download the images one-by-one.

**Comment by mingminzhen** [comment]
Thanks so much.
