### ISSUE TITLE
Annotation tool

### ISSUE THREAD

**Issue by priyanka-chaudhary** [nightrome/cocostuff10k#12]
![cocostuff_error](https://user-images.githubusercontent.com/16559928/33073024-d899283c-cec1-11e7-8736-537b112acd47.JPG)
In Annotation tool,
While doing this step: Extract the thing annotations for all images in Matlab: extractThings()
I get error on Matlab 
Loading and preparing annotations... Undefined function or variable 'gasonMex'
Did anyone had similar issue or know how to fix it?
Thank you!

**Comment by nightrome** [comment]
You will need to install the COCO API as well.
Download it from [https://github.com/cocodataset/cocoapi](https://github.com/cocodataset/cocoapi) and add coco/MatlabApi to the Matlab path.

**Comment by priyanka-chaudhary** [comment]
It was installed automatically by extractThings() and I added the folder to the path manually but still I get the same error.

**Comment by nightrome** [comment]
For the COCO API the authors say that "(OSX/Linux binaries provided)". Are you maybe on Windows? If so, try to compile the files yourself.

**Comment by priyanka-chaudhary** [comment]
Yes I am on windows. I will try that. Slightly off-topic question, can I use this annotator tool to annotate images for a different dataset? For my project I am annotating images for semantic segmentation.

**Comment by nightrome** [comment]
Sure, if you want to annotate superpixels, you can do that for your own images.

**Comment by priyanka-chaudhary** [comment]
Sorry to ask again but when I am compiling gasonMex.cpp, gason.h is giving lots of error. Any idea why would that be?

**Comment by nightrome** [comment]
Hm sorry, I can't help you with that. Either check the the [COCO API](https://github.com/cocodataset/cocoapi) page or that of [Gason](https://github.com/vivkin/gason).

**Comment by Safiullahmarwat** [comment]
@priyanka-chaudhary  how did you mange "compiling gasonMex.cpp, gason.h is giving lots of error" ?I dont know whether I have to compile it for only one time or each time run the code I need to compile the files? any guidance please.

**Comment by RajatGarg45** [comment]
Compiling gasonMex.cpp is giving lot of errors.. Any solution??

**Comment by Mropenai** [comment]
any one solve the problem?

**Comment by nightrome** [comment]
@abdalluhahmed As discussed [above](https://github.com/nightrome/cocostuff10k/issues/12#issuecomment-346033064), this is unfortunately the wrong repository to discuss that.
