### ISSUE TITLE
Could you share the trained Deeplab models?

### ISSUE THREAD

**Issue by xmubingo** [nightrome/cocostuff10k#14]
Hi , for saving time, could you share the trained Deeplab models(resnet101, vgg16)?

**Comment by nightrome** [comment]
Hi, unfortunately this Github project is for the deprecated COCO-Stuff 10K dataset and therefore I will not be making those models available. I will try to make them available for the entire [COCO-Stuff dataset](http://cocodataset.org/#stuff-challenge2017) (165K images), as soon as it is published..
