### ISSUE TITLE
prepare my own data as cocostuff

### ISSUE THREAD

**Issue by dexter1608** [nightrome/cocostuff10k#15]
Hi
I have annotated json files of each image made through (labelme) tool how should I convert this into cocostuff dataset formt?

**Comment by nightrome** [comment]
Hi dexter1608. Thanks for your interest. I am not sure why you would like to bring your dataset in this format. It is actually the standard COCO format. For more information see [http://cocodataset.org/#download](http://cocodataset.org/#download). Maybe you can get some inspiration from [this script](https://github.com/nightrome/cocoapi/blob/master/PythonAPI/cocostuff/internalToCocoGTDemo.py) which converts a bunch of Matlab annotation files in LabelMe format into a single JSON in COCO format.
