### ISSUE TITLE
Loading this dataset by using pycocotools

### ISSUE THREAD

**Issue by zhwuer** [nightrome/cocostuff10k#16]
Hello
I want to load this dataset by using pycocotools but I got this problem 
![2018-01-21 22 01 01](https://user-images.githubusercontent.com/29060417/35194934-d0c77cf2-fef6-11e7-883b-bc03ea8f51f4.png)
And I am quite confused about some part of the file 'cocostuff-10k-v1.1.json'
![2018-01-21 22 02 12](https://user-images.githubusercontent.com/29060417/35194938-dc4d5ff6-fef6-11e7-87cb-3ae5ceba90d8.png)

**Comment by nightrome** [comment]
Hi,
how are you opening the file?
Are you using Windows, Python 3 or anything else that may not be supported by the COCO API?
What confuses you about the json file?

**Comment by zhwuer** [comment]
Thank you so much for your attention!!!
I am using Python 3. Is it unsupported by the COCOAPI ?
I got confused because of the value of "counts", it's so weird, there are so many 0 or O and other odd characters (sorry, i am a freshman T_T )

**Comment by nightrome** [comment]
Yes, Python 3 is known to have a lot of problems. Try 2.x. The weird contents of the segmentation field indicate that the segmentation is RLE encoded ([http://cocodataset.org/#download](http://cocodataset.org/#download)). I would recommend using the [COCO 2017 Stuff Challenge](http://cocodataset.org/#stuff-challenge2017) dataset with 65K images instead of the json from this site!

**Comment by monomon** [comment]
Hey, so I tracked down this error to the way the mask is loaded in pycocotoools, depending on its type - check [here](https://github.com/nightrome/cocoapi/blob/f41d49bd87786da8987f4a96b17b297ab856d8ef/PythonAPI/pycocotools/coco.py#L414).
The segmentation is a list, so it takes the first branch, thinking that the segmentation is a list of ints.

This indicates a slight incompatibility of this dataset with regards to the 65k dataset.
Segmentaitons are recorded as lists of length 1, while they should be dictionaries with "counts" and "size" keys. Perhaps a `squeeze` [somewhere in the conversion code](https://github.com/nightrome/cocostuff/blob/de126a0466576c281070e92efef438b72244b556/dataset/code/conversion/convertAnnotationsJSON.py#L243) could fix this? I'm not well acquainted with it, unfortunately.

This is the reason why pycocotools works with the 65k dataset, but not this one. Seems like an easy enough fix, though it might break backward compatibility.

**Comment by nightrome** [comment]
I am surprised noone else has had any problems with this before (including myself). Try adding [this line](https://github.com/nightrome/cocoapi/blob/master/PythonAPI/pycocotools/cocostuffhelper.py#L32).
In any case you should stop using COCO-Stuff 10k and move to 65k. Soon we'll release the whole [165k on that page](http://cocodataset.org/#download).
