### ISSUE TITLE
Convert to Yolo forman

### ISSUE THREAD

**Issue by RushNuts** [nightrome/cocostuff10k#17]
Hello! I download COCO dataset for training dataset on YOLO. But annotations turns out on .json format. How i convert them to YOLO? YOLO have a .txt labels .

Thanks, and sorry if my question is stupid :-)

**Comment by nightrome** [comment]
Hi, I am not familiar with the YOLO format, but the COCO format is explained here: http://cocodataset.org/#download

**Comment by RushNuts** [comment]
Yeah, i download from here. Annotations in JSON format, therebefore i ask about convert to YOLO. :(
