### ISSUE TITLE
when I look at the classes it only shows the stuff classes in the annotations. 

### ISSUE THREAD

**Issue by JaspervDalen** [nightrome/cocostuff10k#18]
Is the normal annotation (coco) of things not included in the JSON of stuff? As in how would i get the category of every object on an image and not just the category other for all the thing classes?

**Comment by nightrome** [comment]
Both stuff and thing labels are included in the JSON. Just open it in your editor and you will see that the category_id fields correspond to integers 1-182 from: [https://raw.githubusercontent.com/nightrome/cocostuff/master/dataset/cocostuff-labels.txt](https://raw.githubusercontent.com/nightrome/cocostuff/master/dataset/cocostuff-labels.txt)

**Comment by JaspervDalen** [comment]
this is true for the json provided in this repo. However you refer to http://cocodataset.org/#stuff-challenge2017 for more images and in this json it starts at 1 with banner and ends with the category other representing everyting from the thing class.

**Comment by nightrome** [comment]
Yes, but this repo does not have anything to do with the challenge, where all thing classes are merged into a single class. The code for that can be found [here](https://github.com/nightrome/cocoapi), where you can also find and modify the script that merged the stuff and things: [https://github.com/nightrome/cocoapi/blob/master/PythonAPI/cocostuff/internalToCocoGTDemo.py](https://github.com/nightrome/cocoapi/blob/master/PythonAPI/cocostuff/internalToCocoGTDemo.py)

Note that banner has the index 92, so the thing indices (1-91) are still usable and you could just add the original thing annotations from COCO to the same file.

**Comment by JaspervDalen** [comment]
ok thank you. Do you know if the Img ID's in both sets match? Or even the AnnIds? Or do I have to match the filenames?

**Comment by nightrome** [comment]
The image ids certainly match. The annotation ids are somewhat arbitrary. Just remove annotations with the new thing category id from the challenge annotations and add all annotations from COCO.

**Comment by JaspervDalen** [comment]
Ok that should be easy to do thanks! Do you know if the train val split is the same in the stuff and the coco set? Or should I combine them and split them after adding the annotations?

**Comment by nightrome** [comment]
The split is the same, but since the current version does not include all 165k images from COCO yet, the training set of the challenge is a subset of all training images. Val is complete and hence identical.
