### ISSUE TITLE
extractThings Problem

### ISSUE THREAD

**Issue by NIEYALI** [nightrome/cocostuff10k#19]
Thanks for your great work, but I met this following problems:
>> extractThings
Loading COCO API...
Loading and preparing annotations... DONE (t=11.14s).
Error using containers.Map/subsref
The specified key is not present in this container.

Error in CocoApi/getAnnIds (line 121)
        t = coco.loadAnns(coco.inds.imgAnnIdsMap(imgIds));

Error in extractThings>getImLabelMap (line 88)
annIds = cocoApi.getAnnIds('imgIds', imgId, 'iscrowd', []);

Error in extractThings (line 71)
    labelMap = getImLabelMap(cocoApi, image, imageName);

Could u tell me what's wrong here? I use new dataset. And I want to create new annotation of new classes. Thanks a lot.

**Comment by nightrome** [comment]
Thanks for your interest! Are you trying to do this for a dataset other than COCO?
That won't work! You will have to modify [extractThings](https://github.com/nightrome/cocostuff10k/blob/master/annotator/code/extractThings.m) to be able to at least save a dummy labelMap with all zeros.

**Comment by NIEYALI** [comment]
Thanks a lot.
