### ISSUE TITLE
COCO json annotation format?

### ISSUE THREAD

**Issue by ahundt** [nightrome/cocostuff10k#2]
Is cocostuff available in the coco json annotation format?

**Comment by nightrome** [comment]
Unfortunately not yet. In fact we are currently working on annotating **all** images in COCO and the final dataset will be provided in JSON format. Could you tell me what use-case you have in mind?

**Comment by ahundt** [comment]
I have python code that can load the COCO dataset and train a segmentation classifier, so with the same json format I could train on these new annotations simply by changing which annotation file I load. Thanks for the consideration!

**Comment by nightrome** [comment]
Okay, I'll look into it. Only problem is that we don't have a notion of instances, as for the COCO things (1 car = 1 instance). So I guess I'll go with individual superpixels or connected components for now.

**Comment by ahundt** [comment]
Cool! That will actually make this better than the original COCO for my use cases. I'm not using instances at the moment so I didn't consider that difference. Perhaps there is a clean way to handle that that would keep most existing code using  [upstream coco](https://github.com/pdollar/coco) working correctly? 

Some possibilities:

 1. Mark everything as a single instance and clearly explain this discrepancy up front in the docs/comments for the dataset
 2. Provide a patched fork of pycocotools that handles non-instance segmentations
    - Perhaps the [upstream coco](https://github.com/pdollar/coco) would also accept such a pull request if no breaking changes are introduced.
 3. Actually add instance annotations
    - This is super complicated and time intensive so I understand this is likely impractical.

Thanks again for considering this feedback!

**Comment by nightrome** [comment]
Now I have created the [JSON annotations](http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/cocostuff-10k-v1.1.json). The solution I took was to create one annotation (in JSON) per label that is present in an image (not superpixels or connected components). To avoid overlap with the COCO thing labels I mapped the stuff labels to the range 92-182. For more information see [https://github.com/nightrome/cocostuff#json-format](https://github.com/nightrome/cocostuff#json-format).

I would appreciate if you could test the JSON format with your code and see if it behaves the same way as COCO.

**Comment by ahundt** [comment]
Fantastic! With these, should I be able to use the images from the original COCO dataset or should I download your version linked on the readme separately?

**Comment by nightrome** [comment]
Hi, the images are just copied and therefore the original is at least as good. Note that our JSON is just the stuff and no thing annotations, so you'll still need:[http://msvocds.blob.core.windows.net/coco2014/train2014.zip](http://msvocds.blob.core.windows.net/coco2014/train2014.zip)
