### ISSUE TITLE
stuff annotation tool 

### ISSUE THREAD

**Issue by NIEYALI** [nightrome/cocostuff10k#21]
Thanks for your great works. But I have questions : 1. Could this tool make bboxes of objects? 2. Could this tool make captions of single image? 3. Should all parts be labeled as some names?
Thanks a lot.

**Comment by nightrome** [comment]
1) We use [SLICO superpixels](https://github.com/nightrome/cocostuff10k/blob/master/annotator/code/extractSLICOSuperpixels.m) to create masks, which can be converted to boxes. But note that SLICO produces very regular regions and you are more interested in Selective Search or EdgeBox proposals, which we don't use. (but code can be found online)
2) No. We use existing human-annotated captions. If you want that, you need to look for image captioning works.
3) No. We also have an 'unlabeled' label, which we use if none of the other labels applies.
