### ISSUE TITLE
How can I use this tool to annotate another dataset?

### ISSUE THREAD

**Issue by gaqiness** [nightrome/cocostuff10k#23]
I  would like to use this stuff annotation tool to annotate another dataset(like coco-format)
but how can I  generate data/input/regions/***.mat ?

**Comment by nightrome** [comment]
See the [instructions](https://github.com/nightrome/cocostuff10k#annotation-tool). [This code](https://github.com/nightrome/cocostuff10k/blob/master/annotator/code/extractSLICOSuperpixels.m) extracts the superpixels.

**Comment by gaqiness** [comment]
@nightrome 
I want to transfer the *.mat annotation file to a singel *.json annotation file .
I use convertAnnotationsJSON.py this script, but why I need annothor *.json file?
"To run this script you need to download the COCO-Stuff code,
 COCO-Stuff dataset, COCO annotations and COCO API."

**Comment by nightrome** [comment]
That's because it combines our stuff annotations with the COCO thing annotations. You can just go through the code and remove that part. Otherwise take a look at this tutorial: https://patrickwasp.com/create-your-own-coco-style-dataset/
