### ISSUE TITLE
How can I visualize my DeepLab test results?

### ISSUE THREAD

**Issue by night-zhang** [nightrome/cocostuff10k#25]
Hi，

  First of all, thanks for your great work.

  My question is, after I finished training my model, the training process gave me some results for my test set. Those results are in .mat  format. Is there any script that I can use to visualize .mat files (e.g., a script that help me convert .mat file into .png file with different color for different class)? I have been searching a lot but I am not a Matlab guru.

Thanks in advance!

**Comment by nightrome** [comment]
Just use basic Matlab functions:
```
mat = load(fileName);
imagesc(mat.varName); % not sure what the name of the variable is that file
saveas(...)
```
Alternatively look at Matlab functions `ind2rgb` and `imwrite`.
