### ISSUE TITLE
How about the full class list of older cocostuff1.0?

### ISSUE THREAD

**Issue by wangq95** [nightrome/cocostuff10k#26]
Hi, @nightrome , I appreciate for your works, it really helpful. But for fair comparison, I have to evaluate the models on the older COCO_stuff dataset, i.e., vision 1.0. I have no idea about the full class list of it which only contains 172 classes. Can you help me to get these information? Thanks a lot.

**Comment by nightrome** [comment]
Hi. Please read https://github.com/nightrome/cocostuff10k#label-names--indices. All versions of COCO-Stuff have the same 172 classes, but we adjusted the indices to be identical to COCO for the thing classes, as 11 thing classes are empty.
