### ISSUE TITLE
How to extract only the png from mat ?

### ISSUE THREAD

**Issue by cmdrootaccess** [nightrome/cocostuff10k#27]
Hello,

i downloaded the dataset but to only realize that the annotations folder has .mat files instead of png files.

how can i covert these .mat files to png ?

i plan to train them on pytorch deeplab v3

**Comment by nightrome** [comment]
Please see https://github.com/nightrome/cocostuff10k#semantic-segmentation-models.
The script you are looking for is: https://github.com/nightrome/cocostuff10k/blob/5fe3850d547ae4b21d73307dd156dfc5c5c61c5c/dataset/code/conversion/convertAnnotationsDeeplab.m
