### ISSUE TITLE
Unable to convert JSON to t7 format using COCO api

### ISSUE THREAD

**Issue by absurdvision** [nightrome/cocostuff10k#3]
Hi I am trying to convert the provided json file cocostuff-10k-v1.1.json to t7 format using coco api available here. I am using the lua function `coco.CocoApi("cocostuff-10k-v1.1.json") ` to do this. Iam getting an error 
`convert: cocostuff-10k-v1.1.json --> .t7 [please be patient]	
...ri/mnt_hari/torch/install/share/lua/5.1/coco/CocoApi.lua:142: Expected comma or array end but found T_OBJ_BEGIN at character 104320833
stack traceback:
	[C]: in function 'decode'
	...ri/mnt_hari/torch/install/share/lua/5.1/coco/CocoApi.lua:142: in function '__convert'
	...ri/mnt_hari/torch/install/share/lua/5.1/coco/CocoApi.lua:128: in function '__init'
	...hari/mnt_hari/torch/install/share/lua/5.1/torch/init.lua:91: in function <...hari/mnt_hari/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'CocoApi'
	[string "_RESULT={coco.CocoApi("cocostuff-10k-v1.1.jso..."]:1: in main chunk
	[C]: in function 'xpcall'
	...hari/mnt_hari/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	...hari/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x00405d50	
                                                                      [1.4312s]	` 
while running this. Is there a way to do this?

**Comment by nightrome** [comment]
Hi,
could you try with the [latest version of that file](http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/cocostuff-10k-v1.1.json)? It seems that my script was missing a comma.

**Comment by absurdvision** [comment]
It works now.
Thanks for the quick fix
