### ISSUE TITLE
Additional Paths

### ISSUE THREAD

**Issue by niteshbhatia008** [nightrome/cocostuff10k#6]
Matlab is generating following error upon executing "demo_cocoStuff();" after "startup();" 

```
Undefined function or variable 'imageInsertBlobLabels'.
Error in demo_cocoStuff (line 52)
labelMapThingsIm = imageInsertBlobLabels(labelMapThingsIm, labelMapThings, labelNames);
```

Additional paths are required in startup.m for specifying location of extra source files in Matlab 2015b.
```
addpath('dataset/code/utils');
addpath('dataset/code/conversion');
```

**Comment by nightrome** [comment]
Thank you for the advice. I forgot to change the startup script when I created the subfolders.
